### ISSUE TITLE
March 18, 2020 | Code-Review : The Poodles

### ISSUE THREAD

**Issue by sz16900** [Flakster/JARL-Just-Another-Ruby-Linter-#1]
The project is looking good @Flakster. I have one quick suggestion: your rules file is starting to look a bit complex... does it need that much inheritance or can it be split up in different files? Kindly take a look at this and dismiss this if it is not necessary...

**Comment by Flakster** [comment]
Done! You were right @sz16900, the TSE's who reviewed the project agree with you. Thanks for your feedback!
